#.travis.yml

language: node_js

sudo: required

dist: trusty

node_js:
  - 12.4

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master

before_script:
  # set -e causes the script to exit as soon as one command returns a non-zero exit code
  # set -v makes the shell print all lines in the script before executing them, which helps identify which steps failed
  - set -v
  - npm install
  - npm install -g ts-node
  # Create a GUI environment to run ng e2e
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
  - ng lint
  - ng test --code-coverage --browsers ChromeHeadless --watch false
  - ng e2e
  - ng build --prod --base-href /

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - ts-node ./scripts/deploy prod-ci host:${DEPLOY_HOSTNAME} user:${DEPLOY_USER} password:${DEPLOY_PASSWORD} port:${DEPLOY_PORT} dir:${DEPLOY_DIR}

notifications:
  email:
    on_failure: change
    on_success: change
